[package]
name = "launchd-cli"
version = "0.1.0"
authors = ["mikolajwichrowski"]
edition = "2018"

[dependencies]
clap = "2.33"
structopt = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.3"